export { default as NotFoundPage } from "./not-found/NotFoundPage"
export { default as WelcomePage } from "./welcome/WelcomePage"
export * from "./login/LoginPage"
export * from "./home/HomePage"
export * from "./verify-otp/VerifyOtpPage"
export * from "./profile/ProfilePage"
export * from "./search/SearchPage"
